hf = figure;%('Visible','off');
%set(hf, 'Visible','off', 'position',[0 0 1300 1300]);
set(hf, 'MenuBar', 'none');
set(hf, 'ToolBar', 'none');
% set(0, 'CurrentFigure', 1);
% clf reset;
% hf = figure('Visible','off');
grid on;
subplot(1, 1, 1);
XMAX = max(max(Xt));
surf(XX', YY', Xt, 'FaceColor', 'interp', 'EdgeColor', 'k', ...
	'FaceLighting', 'phong');
xlabel('x','FontSize', 22);
ylabel('y','FontSize', 22);
xt = get(gca, 'XTick');
yt = get(gca, 'YTick');
zt = get(gca, 'ZTick');
set(gca, 'FontSize', 22);
zlabel(strcat('X(x, y, ', num2str(t), ')'));
axis([0, 1, 0, 1, 0, 0.6]);
view(-50,30);
camlight left;


hold on;
axes('position',[0.12 0.75 0.25 0.2]);
box on;
set(gca, 'CLim', [0, 1]);
axis off;
contourf(XX', YY', It);
set(gca,'XTick',[]);
set(gca,'YTick',[]);
xlabel('x','FontSize', 18);
ylabel('y','FontSize', 18);
xt = get(gca, 'XTick');
yt = get(gca, 'YTick');
zt = get(gca, 'ZTick');
set(gca, 'FontSize', 18);
colorbar;
hold on;
pcolor(XX', YY', It);
set(gca, 'CLim', [0, 1]);
shading interp;
contour(XX', YY', It, 'LineColor','k');
set(gca, 'CLim', [0, 1]);
title(strcat('I(x, y, ', num2str(t), ')'));
set(hf, 'MenuBar', 'none');
set(hf, 'ToolBar', 'none');
axes('position',[0.4 0.75 0.25 0.2]);
box on;
set(gca, 'CLim', [0, 1]);
contourf(XX', YY', Et);
xlabel('x','FontSize', 18);
ylabel('y','FontSize', 18);
xt = get(gca, 'XTick');
yt = get(gca, 'YTick');
zt = get(gca, 'ZTick');
set(gca, 'FontSize', 18);
set(gca,'XTick',[]);
set(gca,'YTick',[]);
colorbar;
hold on;
pcolor(XX', YY', Et);
set(gca, 'CLim', [0, 1]);
shading interp;
contour(XX', YY', Et, 'LineColor','k');
set(gca, 'CLim', [0, 1]);
title(strcat('E(x, y, ', num2str(t), ')'));
set(hf, 'MenuBar', 'none');
set(hf, 'ToolBar', 'none');
axes('position',[0.68 0.75 0.25 0.2]);
box on;
set(gca, 'CLim', [0, 1]);
contourf(XX', YY', St);
xlabel('x','FontSize', 18);
ylabel('y','FontSize', 18);
xt = get(gca, 'XTick');
yt = get(gca, 'YTick');
zt = get(gca, 'ZTick');
set(gca, 'FontSize', 18);
set(gca,'XTick',[]);
set(gca,'YTick',[]);
colorbar;
hold on;
pcolor(XX', YY', St);
set(gca, 'CLim', [0, 1]);
shading interp;
contour(XX', YY', St, 'LineColor','k');
set(gca, 'CLim', [0, 1]);
title(strcat('S(x, y, ', num2str(t), ')'));
set(hf, 'MenuBar', 'none');
set(hf, 'ToolBar', 'none');